# This file stores configurations for your Shopify app.

scopes = "write_products, read_products, write_inventory, read_inventory, read_orders, write_orders, read_customers, write_customers, write_publications"
